### ISSUE TITLE
通达OA_v11_6_report_bi_sql.py存在两处问题

### ISSUE THREAD

**Issue by G0rdita** [LittleBear4/OA-EXPTOOL#2]
1、标题信息不符
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/40414497/202330688-514a4aab-8c6a-48c7-867d-a30dee4d7537.png">
2、判断200响应包，存在误报
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/40414497/202330801-0707f277-33ce-4d95-993a-8fab85e680ed.png">
应用中
<img width="929" alt="image" src="https://user-images.githubusercontent.com/40414497/202330935-ea7dedbe-7c3b-4e5b-8bc6-c73f043654cb.png">
实际相应包
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/40414497/202330841-73f86b5b-fbac-4959-b37b-4133d05454d0.png">
找了个环境实际测试了下忘截图了，这是用的peiqi大佬的
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/40414497/202331127-17a53e1a-ecb1-4d4a-8809-0c21270a57aa.png">

**Comment by LittleBear4** [comment]
已修复
